# Schema for the configuration files of the Datetime min max module.

field.widget.settings.datetime_min_max:
  type: mapping
  label: 'Date min max display widget settings'
  mapping:
    min:
      type: mapping
      label: 'Minimum'
      mapping:
        input_type:
          type: string
          label: 'Type'
        input_value:
          type: string
          label: 'Value'
        input_modifier:
          type: string
          label: 'Value'
    max:
      type: mapping
      label: 'Maximum'
      mapping:
        input_type:
          type: string
          label: 'Type'
        input_value:
          type: string
          label: 'Value'
        input_modifier:
          type: string
          label: 'Value'
