maxlength_block_class_field: 255
field_type: multiple_textfields
default_case: standard
allow_only_letters_and_numbers: false
block_classes_stored: '{"":"","col-xs-12":"col-xs-12","col-sm-12":"col-sm-12","col-md-6":"col-md-6","col-lg-8":"col-lg-8","col-xl-8":"col-xl-8","col-lg-4":"col-lg-4","col-md-4":"col-md-4","col-sm-5":"col-sm-5","col-xs-5":"col-xs-5","break-lg-control":"break-lg-control","pull-left":"pull-left","col-md-8":"col-md-8","col-lg-12":"col-lg-12","col-xl-12":"col-xl-12","col-md-12":"col-md-12","col-xl-4":"col-xl-4","it-well-blue":"it-well-blue","break-md-control":"break-md-control","container":"container","col-sm-6":"col-sm-6","clearfix":"clearfix","col-xl-3":"col-xl-3","col-lg-3":"col-lg-3","col-md-3":"col-md-3","walk-n-roll-calendar":"walk-n-roll-calendar"}'
enable_attributes: true
enable_auto_complete: true
qty_classes_per_block: 10
items_per_page: 50
enable_special_chars: true
qty_attributes_per_block: 10
enable_id_replacement: true
weight_attributes: null
weight_class: null
weight_id: null
attribute_keys_stored: '[]'
attribute_value_stored: '[]'
attributes_inline: '[]'
