cacheexclude_list: "/plan-your-trip/routes/*\r\n/plan-your-trip/routes"
cacheexclude_node_types:
  blog_page: '0'
  calendar_event: '0'
  directory_item: '0'
  home_frequent_tasks: '0'
  interagency_agreement: '0'
  jobs: '0'
  landing_page: '0'
  neogov_joblisting: '0'
  news: '0'
  page: '0'
  procurement_bid_or_proposal: '0'
  recruitment: '0'
  rider_alerts: '0'
  route: '0'
  tabbed_basic_page: '0'
  travel_training_accomodation: '0'
  vanpool: '0'
