base_url: 'https://its.rideralerts.com/InfoPoint/GTFS-realtime.ashx'
max_age: '60'
allowed_types:
  - Alert
  - TripUpdate
  - VehiclePosition
json_from_object: 1
items:
  -
    detail:
      file:
        - '3532'
      date_from: '2023-04-30'
      date_to: '2023-05-31'
      remove: X
    weight: '1'
