_core:
  default_config_hash: eKR4FfUD7Cp3bXamsCz6GAxh0PCLIZNMa65y2kChIh0
site_key: 6LdvhZwUAAAAAB6fSqAuCSPXy81CMQC1BvoKOlO1
secret_key: 6LdvhZwUAAAAAG0j7WvVj7MQxifc6YELKZG6SLEQ
verify_hostname: false
use_globally: false
widget:
  theme: light
  type: image
  size: ''
  tabindex: 0
  noscript: false
